### ISSUE TITLE
Support for raising hand

### ISSUE THREAD

**Issue by woutf** [ChrisRegado/streamdeck-googlemeet#2]
Google recently added support for virtually raising one's hand in a Meet call. It would be great if I could map that functionality to the Stream Deck

**Comment by gototen** [comment]
I added the ability to raise one's hand, as well as the ability to pin and unpin the current presentation, in my fork.  I built it on Will Norris' fork because I also wanted his chat toggle code as well.  I can create a PR once his work is brought into the project, or I can make a PR directly to the main repo if others prefer.

https://github.com/gototen/streamdeck-googlemeet/tree/hand-raise-pin-presentation

**Comment by ChrisRegado** [comment]
@gototen Yes, please feel free to send over a PR! Will's changes are all in this repo. GitHub just shows them out-of-sync because his PR was squash merged.

**Comment by mhall** [comment]
@gototen it would be awesome to get a PR for this to the main repo when you have bandwidth :) I've hacked it into my local copy, but there have been some upstream changes so it might need some tweaking for consistency.

**Comment by gototen** [comment]
Sure!  I'm going to move this to a fork directly off of the main project and then open the PR there.

**Comment by gototen** [comment]
@mhall FYI I created a new PR against main.  It shouldn't be too long till it's merged.

**Comment by ChrisRegado** [comment]
[Release v1.2.0](https://github.com/ChrisRegado/streamdeck-googlemeet/releases/tag/v1.2.0) is now published with a Raise/Lower Hand button.

**Comment by mhall** [comment]
@gototen Thanks so much for doing this! It works great!
