### ISSUE TITLE
Only open Meet is working

### ISSUE THREAD

**Issue by brudze** [ChrisRegado/streamdeck-googlemeet#20]
Really looking forward to getting this working.  I got the stream deck just to be able to control Meet. 
I followed the instructions, only Open Meet button is working.
Mic and Camera Toggle showing disconnected

Streamdeck Mini
  Software Version 5.0.0 (14247)
  firmware 3.00.001
Chrome: Version 94.0.4606.54 (Official Build) (x86_64)
MacOS: 11.6

**Comment by ChrisRegado** [comment]
Sounds like the browser extension isn't working for you. 

Just to clarify, you followed all of the Chrome extension setup instructions as well?

In your Chrome Extensions settings window (`chrome://extensions/`), can you make sure Developer Mode is on, and then try a Meet call and click the camera/mic mute buttons on the Meet website a few times? Then check if there's a red Errors button for Stream Deck Google Meet Actions on the Extensions page. If so, can you click that and share the errors?

**Comment by brudze** [comment]
Yes, followed the directions and loaded the unpacked extension.  Tried the clicking mic/camera buttons on web interface many times for Meet.  No errors seen.

**Comment by ChrisRegado** [comment]
Hmm, odd...

If you haven't yet restarted the Stream Deck app since installing the Meet plugin, please give that a try. Or just restart your computer to be safe.

If you open the Chrome console (<kbd>Option</kbd> + <kbd>⌘</kbd> + <kbd>J</kbd>), go to meet.google.com, and then start a call and click the mute buttons in the web browser, are there any errors shown in the console? Keep an eye out for errors like `WebSocket connection to 'ws://127.0.0.1:2394/' failed` or `content blocked` in particular.

On your Mac, is there a file in the folder `/Users/<your_username>/Library/logs/StreamDeck` named `com.chrisregado.googlemeet0.log` (or any other numbers at the end there)? If so, can you attach that here.

Do you have any sort of third-party firewalls on your computer (e.g. Little Snitch), or other browser extensions that might interfere with network connectivity? (Maybe some extra security software if this is a work computer?) The plugin opens port 2394 on localhost, and the browser extension tries to connect to it. If anything blocks that network connection, it would cause the same symptoms you reported.

**Comment by brudze** [comment]
I did uninstall the extension and plugin and retried.  Then i restarted the computer.  no dice.

in the console, no errors due to click the mic and camera buttons. No websocket errors, didn't find 2394 in any of the errors.  No blocks. The meet content errors are 'DevTools failed to load source map: Could not load content ' error 404.  a few deprecation errors also.

In the Library/logs/StreamDeck folder there are 6 files StreamDeck0.log through StreamDeck5.log. attached the most recent log file.
[StreamDeck0.log](https://github.com/ChrisRegado/streamdeck-googlemeet/files/7221417/StreamDeck0.log)
.

Possible work is closing down the port.  How can I check to see if the port is being closed down?

**Comment by ChrisRegado** [comment]
If you open up Terminal and run `nc -vz localhost 2394`, it should say Connection Succeeded. If you then quit the Streamdeck app entirely (right click it in the mac menu bar icon and Quit Stream Deck), and run that same command again, it should say Connection Refused.

It's odd though that you're not seeing any errors in the Chrome console at all. If network traffic was blocked, I'd expect to see websocket failure messages every 2-3 seconds. It kind of sounds like the browser extension isn't even launching. In the Chrome Extension settings again, if you click the Details button on the extension, it should look something like this:

![screenshot_settings](https://user-images.githubusercontent.com/1444732/134606340-100e2cf9-6f0c-4a97-a558-6ad8908f2d64.png)

Also, let's make sure there is no Chrome enterprise policy blocking browser extensions. https://support.google.com/chrome/a/answer/9024365?hl=en describes how to check. You shouldn't see anything related to "extension" on the policy page ( chrome://policy/ ).

**Comment by brudze** [comment]
Using terminal with Stream Deck closed, 100% of the time I get:
nc: connectx to localhost port 2394 (tcp) failed: Connection refused

Stream Deck opened:
50% of the time I get:
nc: connectx to localhost port 2394 (tcp) failed: Connection refused
Connection to localhost port 2394 [tcp/ms-olap2] succeeded!

The rest are:
Connection to localhost port 2394 [tcp/ms-olap2] succeeded!

For the Extension Settings, it looks just like yours except it is off for Incognito mode.

Enterprise policy in place: ExtensionInstallBlocklist, ExtensionInstallForcelist, and ExtensionSettings.  I'll contact my technical support and see if opening that port is an option.

**Comment by ChrisRegado** [comment]
Yup, there's a good chance that's the problem. It means the Stream Deck plugin part is working fine, but the browser extension isn't.

The two things to check with them are:
1. Does anything block Chrome from contacting localhost port 2394.
2. Do they block unknown extensions.

In particular, that `ExtensionInstallBlocklist` setting can be used to block your browser from using all extensions except those approved by your administrator. On a typical installation of Chrome like you might have on your home personal computer, you wouldn't see `ExtensionInstallBlocklist` set at all on the policy page.
