### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by etbox35** [ChrisRegado/streamdeck-googlemeet#5]
Sorry if this is a dumb question, but i cannot control anything, the title on the Stream deck button
says Disconnected. How can I fix this? I installed the extension, reloaded the page, removed and added the extension
and the key but nothing worked.

**Comment by ChrisRegado** [comment]
It would be helpful to see the Chrome error logs for the extension so we can try to figure out how it's failing.

1. First, try fully killing and restarting the Elgato Stream Deck desktop app. (To quit it on Windows, right click and quit the Stream Deck icon in the Windows System Tray. On Mac, right click and quit on the Mac menu bar icon.) Or just restart your computer. Sometimes the Stream Deck app seems to not properly start new plugins after you install them.
2. Open a new tab/window in Chrome.
3. Go to the triple-dot settings button, then More Tools --> Developer Tools, and keep the Console panel that opens on your screen.
4. Go to https://meet.google.com/ in that same tab, start/join a meeting, and click a mute/unmute button on the web site a couple of times.
5. You should see red errors appear in the Console panel that we opened earlier. Right click on any of the red ones, click Save As, and attach the log to this GitHub issue. (We're trying to do [this process](https://support.cloudhq.net/how-to-collect-google-chrome-browser-logs/), but for Meet instead of Gmail.)

**Comment by etbox35** [comment]
[meet.google.com-1613033989167.log](https://github.com/ChrisRegado/streamdeck-googlemeet/files/5963978/meet.google.com-1613033989167.log)

**Comment by etbox35** [comment]
Here you go. I tried everything you said, but it still says disconnected.

**Comment by ChrisRegado** [comment]
Thanks for uploading the log. I think there are two problems here:

1) Unfortunately, this plugin only works for users with an English language setting on your Google account at this time. Based on the logs it looks like your browser locale is set to Czech. (That part's fine, but I assume your Google account language is set to Czech as well.) This plugin works by searching the Meet web interface for human-readable accessibility tags like "microphone" and "camera" in English, and it can't interact with Meet if it doesn't find them.

2) For some reason, the browser extension is failing to connect to the Stream Deck app.
```
contentScript.js:25 WebSocket connection to 'ws://127.0.0.1:2394/' failed: Error in connection establishment: 
net::ERR_CONNECTION_REFUSED
```
This could be for a number of reasons, including your OS or browser proxy settings redirecting traffic for local addresses, or the Stream Deck plugin failing to start. If problem 1 isn't a deal breaker for you and you want to keep investigating, the next place to look is the Stream Deck logs which you can find at `/Users/<username>/Library/Logs/StreamDeck/StreamDeck0.log` on a Mac or `C:\Users\<username>\AppData\Roaming\Elgato\StreamDeck\logs\StreamDeck0.log`.

**Comment by etbox35** [comment]
Oh, ok it was caused by the language. Thank you!

**Comment by ChrisRegado** [comment]
Quick update here. As of [release v1.2.0](https://github.com/ChrisRegado/streamdeck-googlemeet/releases/tag/v1.2.0), all buttons except the new Raise/Lower Hand button should work in any language.
